version: "3.8"

services:
  zypher-agent:
    image: zypher-agent:latest
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      # Container detection (optional - auto-detected)
      - CONTAINER=true

      # Method 1: Environment Variable Authentication
      # Uncomment and set these for direct token authentication
      # - MCP_GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
      # - MCP_GITHUB_REFRESH_TOKEN=${GITHUB_REFRESH_TOKEN}

      # Method 2: Force Device Code Flow
      # This will prompt for browser authentication on the host
      - MCP_GITHUB_AUTH_STRATEGY=device_code

      # Optional: Custom OAuth configuration
      - MCP_GITHUB_DEVICE_CODE_TIMEOUT=600 # 10 minutes
      - MCP_GITHUB_DEVICE_CODE_POLLING_INTERVAL=5 # 5 seconds

      # Debug OAuth issues
      - DEBUG=oauth

    volumes:
      # Persist OAuth tokens between container restarts
      - oauth_data:/app/data/oauth

      # Mount workspace for agent operations
      - ./workspace:/app/workspace

    ports:
      # API server port (if running API mode)
      - "3000:3000"

    # Use init to handle signals properly
    init: true

    # Restart policy
    restart: unless-stopped

volumes:
  oauth_data:
    driver: local

# Example network configuration for multiple containers
networks:
  default:
    name: zypher-network
